apiVersion: {{ template "qbittorrent.deployment.apiVersion" . }}
kind: Deployment
metadata:
  name: {{ template "qbittorrent.fullname" . }}
  labels:
    app: {{ template "qbittorrent.fullname" . }}
    chart: {{ template "qbittorrent.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "qbittorrent.fullname" . }}
      release: {{ .Release.Name | quote }}
  {{- with .Values.strategy }}
  strategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  template:
    metadata:
      labels:
        app: {{ template "qbittorrent.fullname" . }}
        chart: {{ template "qbittorrent.chart" . }}
        release: {{ .Release.Name | quote }}
    spec:
      {{- with .Values.securityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      restartPolicy: Always
      containers:
      - name: {{ template "qbittorrent.fullname" . }}
        image: {{ template "qbittorrent.image" . }}
        imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
        securityContext:
          privileged: true
        env:
        - name: VPN_ENABLED
        {{- if .Values.vpn.enabled }}
          value: "yes"
        {{- else }}
          value: "no"
        {{- end }}
        - name: VPN_USERNAME
          valueFrom:
            secretKeyRef:
              key: username
            {{- if ne .Values.vpn.credentials.secret.name "" }}
              name: {{ .Values.vpn.credentials.secret.name }}
            {{- else}}
              name: {{ template "qbittorrent.fullname" . }}
            {{- end }}
        - name: VPN_PASSWORD
          valueFrom:
            secretKeyRef:
            {{- if ne .Values.vpn.credentials.secret.name "" }}
              name: {{ .Values.vpn.credentials.secret.name }}
            {{- else}}
              name: {{ template "qbittorrent.fullname" . }}
            {{- end }}
              key: password
        - name: LAN_NETWORK
          value: {{ default "10.0.0.0/8" .Values.vpn.lanNetwork | quote }}
        {{- range $key, $value := .Values.extraEnvVars }}
        - name: {{ $key }}
          value: {{ $value | quote }}
        {{- end }}
        ports:
        - containerPort: {{ .Values.uiPort }}
          name: http
          protocol: TCP
        - containerPort: 8999
          name: transport-tcp
          protocol: TCP
        - containerPort: 8999
          name: transport-udp
          protocol: UDP
        volumeMounts:
        - name: qb-data
          mountPath: /config
        - name: qb-downloads
          mountPath: {{.Values.persistence.downloads.mountPath}}
        - name: vpn-config
          mountPath: /openvpn
        livenessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 10
          timeoutSeconds: 30
          failureThreshold: 6
        readinessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 10
          timeoutSeconds: 30
          periodSeconds: 30
        {{- with .Values.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
      dnsPolicy: None
      dnsConfig:
        {{- with .Values.dnsConfig }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      volumes:
      - name: qb-data
      {{- if and .Values.persistence.data.enabled .Values.persistence.data.createClaim }}
        persistentVolumeClaim:
          claimName: {{ template "qbittorrent.fullname" . }}-data
      {{- else if and .Values.persistence.data.enabled (not .Values.persistence.data.createClaim) }}
        {{- with .Values.persistence.data.volume }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- else }}
        emptyDir: {}
      {{- end }}
      - name: qb-downloads
      {{- if and .Values.persistence.downloads.enabledtrue .Values.persistence.downloads.createClaim }}
        persistentVolumeClaim:
          claimName: {{ template "qbittorrent.fullname" . }}-downloads
      {{- else if and .Values.persistence.downloads.enabled (not .Values.persistence.downloads.createClaim) }}
        {{- with .Values.persistence.downloads.volume }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- else }}
        emptyDir: {}
      {{- end }}
      - name: vpn-config
        secret:
          secretName: {{ template "qbittorrent.fullname" . }}-vpn-config
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
