{{- if and .Values.persistence.downloads.enabled .Values.persistence.downloads.createClaim  -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "qbittorrent.fullname" . }}-downloads
  labels:
    app: {{ template "qbittorrent.fullname" . }}
    chart: {{ template "qbittorrent.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
spec:
  accessModes:
    - {{ .Values.persistence.downloads.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.downloads.size | quote }}
  {{- if .Values.persistence.downloads.storageClass }}
  storageClass: {{ .Values.persistence.downloads.storageClass | quote }}
  {{- end }}
{{- end -}}

