{{- if and .Values.vpn.credentials.secret.create  -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "qbittorrent.fullname" . }}
  labels:
    app: {{ template "qbittorrent.fullname" . }}
    chart: {{ template "qbittorrent.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
type: Opaque
data:
  username: {{.Values.vpn.credentials.username | b64enc | quote }}
  password: {{.Values.vpn.credentials.password | b64enc | quote }}
{{- end -}}
